### ISSUE TITLE
Character Aid has only temporary default description

### ISSUE THREAD

**Issue by sirtet** [ewerybody/a2.modules#1]
Needs to be done...

**Comment by ewerybody** [comment]
Yea the whole module thing is rather placeholder at this time. I still need to implement some user interface elements to be able to port more of the original activAid extensions.

The `umlaut` functionality will most probably move to a kind of for-germans-on-english-keyboard module anyway.

**Comment by ewerybody** [comment]
`Character Aid` needs to have it's own port from ac'tivAid. For the meantime this was renamed to texTools and tagged `wip`
