### ISSUE TITLE
Are more modules in work or in planning?

### ISSUE THREAD

**Issue by sirtet** [ewerybody/a2.modules#24]
My favourites are still missing ;-)
[RecentDirs](#29)
[ReadingRuler](#30)
[FileRenamer](#31)

And, how much work is it to translate these, or rather modules in general from ac'tivaid?
I guess it depends... but maybe more can be said about that?

**Comment by ewerybody** [comment]
@sirtet We might have issues for each of these! :)
Do you need ALL of the functionality in there? Are there things that you never used on one of these?

**Comment by ewerybody** [comment]
Hey @sirtet I just created [Issues](#29)  [for](#30)  [each](#31) of these. Can you report on each of what you expect there? Also some documentation would be nice.
