### ISSUE TITLE
Bug: No way to add Source, so a2 is unusable

### ISSUE THREAD

**Issue by Moosbueffel** [ewerybody/a2.modules#39]
I installed a2 with the installer and it is installed in the ../Appdata/Local.. No errors.

Next step is to add source to use this tool. 
Choosing "Add Source - featured - a2.modules " get the error:
![grafik](https://user-images.githubusercontent.com/7726457/107343424-95d61600-6ac1-11eb-9fec-021295c48811.png)

The mentioned url is present and I can find a zip file with the packages!? But I have no plan how to handle this as a workaround. Can I copy a SubDirectory of the .zip to the installations folder to work? And in which subfolder?? Does a2 than autodetect this package?

Any help till fixing the bug apreciated.

 
Thanks for the great work till here. If you like support in documetation, you can contact me.

**Comment by ewerybody** [comment]
Can confirm! Dang! I thought I fixed this long ago :/
I guess you also had the error in the Console tab:
```
ERROR:a2widget.a2module_source:Error: No repository url found in fetched data!
```
This has been fixed! I'll pack another release later on :) brb

**Comment by Moosbueffel** [comment]
Many thanks for rapid Feedback and fixing
Yes, I have this msg in the console.

09.02.2021 12:47:44 Eric Werner <notifications@github.com>:

**Comment by ewerybody** [comment]
Sorry I didn't add another note but I made the release! Pchew! 😅
There is [a new a2 version](https://github.com/ewerybody/a2/releases/tag/0.0.11) out and also [a new a2.modules](https://github.com/ewerybody/a2.modules/releases/tag/0.0.8)!

**Comment by Moosbueffel** [comment]
Now it works :-)
