### ISSUE TITLE
hotstring export/import functionality

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2.modules#5]
Add "import" and "export" buttons to the UI in order for the user to be able to save his list.

**Comment by ewerybody** [comment]
Read and write back from/to hotstring format?

**Comment by lipkau** [comment]
why hotstring format?
I would have suggested to just save a copy of the file, and the ui refreshes the list of hotkeys according to what is in the file

**Comment by ewerybody** [comment]
Well ac'tivAid has hotstring format only and the only written thing we have now is also like that. Meaning: _Autohotkey readable hotstring code_.
Exporting the JSON from the DB shouldn't be too hard either and importing such.
A python based hotstring code parser is a little heavier to do. But absolutely doable! 👍

**Comment by lipkau** [comment]
I think the ahk file hosting.ahk would be enough.
But only if the importing works

**Comment by ewerybody** [comment]
This will probably goto the module menu not to clutter the main hotstrings interface: https://github.com/ewerybody/a2/issues/173
