### ISSUE TITLE
Module CommandLine is not the same as in ActivAid

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2.modules#6]
In ActivAid, the plugin "CommandLine" enables the user to run a command in the shell from the address bar of the explorer.exe
The a2 "CommandLine" enables the user to use key combinations that Windows does not allow in the shell

* [x] Should both behaviors be merged into the a2's CommandLine?
* [ ] Should a2's CommandLine be renamed?
* [ ] Should activ'aid's CommandLine be renamed?

**Comment by ewerybody** [comment]
Each of them is not super extensive. I think we can easily merge them into one :]

**Comment by ewerybody** [comment]
e8173ed
