### ISSUE TITLE
ExplorerCreateFile: set encoding of new files content

### ISSUE THREAD

**Issue by ewerybody** [ewerybody/a2.modules#60]
@Cyberkabauter contributed an idea in [a2#250](https://github.com/ewerybody/a2/issues/250):
> It would be great, if I could define the fileformat of the textfile (UTF8 and so on)

Yes! Good idea! I wonder if that acually works if there is no content given yet but it all comes down to the capabilities we get from Autohotkeys [`FileEncoding`](https://www.autohotkey.com/docs/commands/FileEncoding.htm)

**Comment by Cyberklabauter** [comment]
Yes, should work with FileEncoding :).

**Comment by ewerybody** [comment]
Hey @Cyberklabauter its in! :)
![image](https://user-images.githubusercontent.com/218956/153167249-7cd6506a-9a47-42fb-942e-24ee4ae5517b.png)

**Comment by ewerybody** [comment]
Ah ok 👍 I was just grabbing the exact terms from the [FileEncoding](https://www.autohotkey.com/docs/commands/FileEncoding.htm) docs, added them to the [ui/a2ahk.py](https://github.com/ewerybody/a2/blob/c369a4e28d8b869d90957451140ccc690599138c/ui/a2ahk.py#L12) and filled the menu like that. 

I wouldn't have thought that these are needed. But here we have a request :) I wonder how I'd do the "any" codepage thing.

And just to clarify: The RAW ones are the BOM ones? I think I'll add a link to the Autohotkey docs right in the menu...

**Comment by ewerybody** [comment]
OK. For now I put an integer to set the encoding from that short list .. 
So I'll just change it to be a string then. Just need to match the display names to the actual names from the docs to be accepted by the command. Its a little more fiddly but not too bad.

The thing with the opening ... sorry for being so picky with this but this would be out of the scope of this issue. Moved it to a new one #66 :)

**Comment by ewerybody** [comment]
wip: Docs link already works as well 👍
![image](https://user-images.githubusercontent.com/218956/153520675-18663357-c38a-4081-a63a-d779ad1b9eee.png)

**Comment by Cyberklabauter** [comment]
You are fast. Wow. I think it adresses a smaller group of users. Anyways, it is quite powerfull option, to create files very quickly which matching your needs. 

Thank you!

> And just to clarify: The RAW ones are the BOM ones? I think I'll add a link to the Autohotkey docs right in the menu...

Sorry: This was misleading. Somehow I wrote it upside down. Of course RAW stands for **WITHOUT BOM** ([Byte Order Mark](https://de.wikipedia.org/wiki/Byte_Order_Mark)). 
- UTF-8 RAW
- UTF-8 (with BOM)
- UTF-16 RAW
- UTF-16 (with BOM)

**Comment by ewerybody** [comment]
Ah Ok I see. looking at [the docs](https://www.autohotkey.com/docs/commands/FileEncoding.htm) it looks like their order is rather:
* UTF-8 (with BOM)
* UTF-8 RAW
* UTF-16 (with BOM)
* UTF-16 RAW

🤔 But the "standard" encoding in these terms would be `UTF-8 RAW` is that correct?

Now .. I think I'll remove this `CONST` and make it a JSON in the module folder
with `key`:`value` pairs like `ValidAHK-Encoding`:`Display Name`

**Comment by Cyberklabauter** [comment]
Yes, As I know the UTF-8 Specifications recommend UTF.8 without BOM. But this topic is quite confusing and I am not an expert on it. AHK usually adds a BOM; From the FAQ:

> To read other UTF-8 files which lack a byte order mark, use [FileEncoding](https://lexikos.github.io/v2/docs/commands/FileEncoding.htm) "UTF-8-RAW", the *P65001 option with [FileRead](https://lexikos.github.io/v2/docs/commands/FileRead.htm), or "UTF-8-RAW" for the third parameter of [FileOpen](https://lexikos.github.io/v2/docs/commands/FileOpen.htm). The -RAW suffix can be omitted, but in that case any newly created files will have a byte order mark. [look at the AHK FAQ](https://lexikos.github.io/v2/docs/FAQ.htm#nonascii) 

I interpret this, that if you don't use the UTF-8-RAW option (which most scripts won't do) with FileRead or FileOpen BOM is automatically added to the string and represented in each files you will save the string to.

**Comment by Cyberklabauter** [comment]
I just had a look at my notes why I use BOM with my AHK scripts: Lexikos recommended it, so I decided to go with it:

> My recommendation for AutoHotkey v1 is still UTF-8 with BOM. UTF-8 without BOM will not work without the /cp65001 command line switch, such as with portable AutoHotkey.exe or without the UTF-8 option enabled in the installer.
> The top line of the FAQ does not specify with or without BOM. In all but the most recent versions of Notepad, UTF-8 with BOM is just "UTF-8", and ANSI is the default. AutoHotkey does not exclusively run on the latest Windows 10 builds. Further down the FAQ says "To save as UTF-8 in Notepad, select UTF-8 or UTF-8 with BOM from the Encoding drop-down in the Save As dialog", but either option could include a BOM, depending on the Notepad version. ([Source]https://www.autohotkey.com/boards/viewtopic.php?p=345161#p345161) )

**Comment by ewerybody** [comment]
having defaults is a new issue now :) #67
