### ISSUE TITLE
OCRTool: set language not passed to script

### ISSUE THREAD

**Issue by ewerybody** [ewerybody/a2.modules#62]
@Cyberkabauter reported an issue [a2#250](https://github.com/ewerybody/a2/issues/250):
> I try to use OCR with the german language but alsways get the error message “Can not use language "en" for OCR, please install language pack.” (even I want to use the german language for OCR).
After several attemps a2 stop working cursor remains as crosshairs.
> 
> Also a hint, which language pack has to be installed would be helpful. I guess it is the Windows OS language pack.

Oh darn! A look into the script code reveals the problem:
https://github.com/ewerybody/a2.modules/blob/455ea279f9ebf96205ed71aa49fea952842b7ce7/ocr_tool/ocr_tool.ahk#L33-L34

I actually bypassed the direct call to the ocr script and implemented an additional off process call to mitigate [a weird COM-error I used to have and didn't get solved through the forum](https://www.autohotkey.com/boards/viewtopic.php?p=380651#p380651) and forgot to implement passing along the language! Which [defaults to english](https://github.com/ewerybody/a2/blob/254c86292f019ae3a3fe963bde35a95bdf052c26/lib/Autohotkey/lib/teadrinkerocr.ahk#L16) 🤦‍♀️!!
But I can switch that back in dev now and see how things turn out. Maybe we can have the bypass be used optionally only in case it breaks. I wouldn't like to have a weird option in the UI to deal with these things.

- [x] rollback off-process hack
- [x] fix hack to have language passed along
- [ ] make script use hack in case of the error

Oh and there are more things! OK: we apparently need some custom UI for this. Of course I don't have a list-language-packs-button ... yet! So eventually:
- [ ] #65
- [ ] offer a button to goto the dialog/website to download language packs

**Comment by Cyberklabauter** [comment]
Did you notice this [comment](https://www.autohotkey.com/boards/viewtopic.php?p=410742#p410742) and the following hints from teadrinker and malcev?

**Comment by ewerybody** [comment]
Oops. No I didn't 🙈
But seems they went about the fact that the script was fed with a path and a bitmap object in each case. Whereas I had it within the main a2 runtime or as a separate process... Each time with the same input. 🤔.

**Comment by Cyberklabauter** [comment]
Just thought I mention it because it may a hint there problem could be.

**Comment by ewerybody** [comment]
Yeah true I could have read into it already (I'm kinda lazy with the forum) but I just enabled the email notifications for that :D
I still need to dig deeper into what they came up with. But the weekend is rather busy here....

**Comment by ewerybody** [comment]
OK. rolled back to runtime functionality. Work for me so far...
