### ISSUE TITLE
VolumeControl: catch too many hotkey activations

### ISSUE THREAD

**Issue by ewerybody** [ewerybody/a2.modules#64]
@Cyberkabauter in [a2#250](https://github.com/ewerybody/a2/issues/250): 

> Using it with an touchpad it quickly results in the errormessage “71 hotkeys have been received in the last 1375ms. Do you want to continue? You may want to fix that by increasing #[MaxHotkeys](https://www.autohotkey.com/docs/commands/_MaxHotkeysPerInterval.htm)

Hahaaa! I actually just ported it for when I'm on a desktop PC with a Mouse attached :D
My laptop has something built-in already with gestures on the touchpad.

But anyway: this should never happen! 👍 .. reading the warnings on the docs page tho: we should rather prevent it from being trigerable so darn often than setting `#MaxHotkeysPerInterval` for the whole ahk runtime globally!

**Comment by ewerybody** [comment]
I just tried it myself: Can confirm that it's easy to make it snap with the touchpad 👍
Now just adding a small `Sleep, 25` seems to fix it already! And still feels responsive enough.

**Comment by Cyberklabauter** [comment]
Perfect, sounds great!

**Comment by ewerybody** [comment]
OK. I upped the version of the module but the release of the package will take a couple days. But I'm looking forward to making a new one pretty soon! :)

**Comment by Cyberklabauter** [comment]
Cool. Looking forward to it. It makes fun to follow you progress. 👍
