### ISSUE TITLE
Finish SessionRestore module

### ISSUE THREAD

**Issue by ewerybody** [ewerybody/a2.modules#8]
There is already quite some code regarding this and the process is kinda nailed down. But first:

What am I trying to solve: Windows 10 is constantly shifting around my meticulously arranged windows and desktop icons when I log back in or have been connected through VPN.

In SessionRestore you'll be able to collect window descriptions that when match will be rearranged on demand or when you log back in if the screen sizes also match.

Process of rearranging multiple subwindows:
* gather window list (without hidden windows)
* restore ALL windows with processes that are in our list
* gather new window list, this one will have all the subwindows too (without digging through hidden windows)
* loop the list
  * check window against our list, rearrange if needed and minimize if it was minimized before
  * if wanted restore and hide any minimized window to render the Alt+Tab preview

**Comment by ewerybody** [comment]
we probably need less checkboxes, more a kind of form layout for the prefs of a window.
```
   process name: notepad++.exe
     class name:
   window title:
top left corner: 435, 633
 width & heigth: 300, 345
                [ ] ignore
```

**Comment by lipkau** [comment]
I don't understand. Are these notes or do you want my opinion?

**Comment by ewerybody** [comment]
notes

**Comment by ewerybody** [comment]
If you have an opinion about it: Well, let it out!! :) 👍

**Comment by ewerybody** [comment]
This main loop in implemented. I'll gather smaller tasks is new issues.
